# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Amluto.Steps
PackageVersion: 0.4.2
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://steps.amluto.com/download/amluto-steps-0.4.2-x64-setup.exe
  InstallerSha256: 786F6C82366BABCAE686D1B74D984348E6076F2723DA37EBD58EB9B5D8EB6E53
  ProductCode: Steps
  AppsAndFeaturesEntries:
  - DisplayName: Steps
    Publisher: Amluto Solutions Ltd
    ProductCode: Steps
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://steps.amluto.com/download/amluto-steps-0.4.2-x64.msi
  InstallerSha256: D47C53154EA90C4429700192F74E9B18F80504284A907447DA74EF7F864C16D5
  ProductCode: '{7D85DF4E-7965-4C1F-B295-E5C51017F3F1}'
  AppsAndFeaturesEntries:
  - DisplayName: Steps
    Publisher: Amluto Solutions Ltd
    ProductCode: '{7D85DF4E-7965-4C1F-B295-E5C51017F3F1}'
    UpgradeCode: '{A8772EA5-E41C-5D68-862D-0BE9828A10A7}'
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-09-30
